### PR TITLE
Side-bar logic and design debugged

### PR DESCRIPTION
**Pull request by OWAIS221B**
Side-bar logic is almost like as previous one i.e. nav bar. The difference was the logic was written for side-bar container. Took some time to look out for CSS as it was not functioning, so had to debug it.

### CODE REVIEW

**Review by waqasmanit — APPROVED** [review]
Nice Progress !!

**Comment by OWAIS221B** [comment]
> Nice Progress !!

Thanks.

**Comment by waqasmanit** [comment]
when creating PR, always attach screenshot like this

Screenshot (3)

**Comment by waqasmanit** [comment]
Remove Project from "Modal Project"

**Pull request merged**
